/**
 * App icon (512x512 PNG) embedded as base64.
 *
 * Inlining keeps the Worker a single self-contained module: no static-asset
 * pipeline, no extra R2 round-trip, and it survives `wrangler deploy` untouched.
 * At ~2.4 KB the bundle cost is negligible.
 */
const ICON_B64 =
  'iVBORw0KGgoAAAANSUhEUgAAAgAAAAIACAIAAAB7GkOtAAAJbklEQVR42u3dwQ2cUBAFQaJAHIiQzIgSUkCcYLqkioB989s+' +
  'WF7WbQcgaPEJAAQAAAEAQAAAEAAABAAAAQBAAAAQAAAEAAABAEAAABAAAAQAAAEAQAAAEAAABAAAAQBAAAAQAAAEAAABAEAA' +
  'AAQAAAEAQAAAEAAABAAAAQBAAAAQAAAEAAABAEAAABAAAAQAAAEAQAAAEAAABAAAAQBAAAAQAAAEAAABAEAAAATAVwAQAAAE' +
  'AAABAEAAABAAAAQAAAEAQAAAEAAABAAAAQBAAAAQAAAEAAABAEAAABAAAAQAAAEAQAAAEAAABAAAAQAQAAAEAAABAEAAABAA' +
  'AAQAAAEAQAAAEAAABAAAAQBAAAAQAAAEAAABAEAAABAAAAQAAAEAQAAAEAAABAAAAQAQAF8BQAAAEAAABAAAAQBAAAAQAAAE' +
  'AAABAEAA+ITjvOAJxyIAeOtBFQQA7z4ogQDg6QcZEAA8/ciAGxQAvP5oAAKApx8ZQADw+qMBCABefzQAAcDrjwYgAHj90QAE' +
  'AK8/GoAAIAAIAAKA1x8NQAC8/qABCIAAgAAgAF5/0AAEQABAABAArz9oAAIgACAACIAAgAAgAF5/0AAEQABAAAQAAQABEAAE' +
  'AARAABAAEAABQABAAAQAAQABEAC8/qABAoAAgAAIAAIAAiAACAAIgAAgAAgAAoAAIAAIAAKAACAACAACgAAIAAgAAiAAIAAI' +
  'gACAACAAAgACgAAIAAgAAiAAIAAIgACAACAAAgACgAAIAAgAAiAAIAACgACAAAgAAgACIAAIAAiAACAAIAACgACAAAgAAgAC' +
  'IAAIAAiAACAAIAACgACAAAgAAoAAIAAIAAKAACAACAACgAAgAAgAAoAAIAACAAKAAAgACAACIAAgAAiAAIAAIAACAAKAAAgA' +
  'CAACIAAgAAiAAIAAIAACAAIgAD6BAIAACAACAAIgAAgACIAAIAAgAAKAAIAACAACAAIgAAgACIAAIAAgAAKAAIAACAACAI5a' +
  'ABAABAABQAAQAAQAAUAAEAAEAAFAAAQABAABEAAQAARAAEAAEAABAAFAAAQABAABEAAQAARAAEAAEAABAAFAAAQABAABEAAQ' +
  'AAFAAEAABAABAAEQAAQABEAAEAAQAAFAAEAABIBYAPwuxmM8AkDohv0WhmRIAkDubv0K5mROAkDxYv0EFmVRAkDxXH1/ozIq' +
  'AcCtYlRGJQBkbtXHtyu7EgAcKnZlVwKAQ8Wu7EoAcKjYlV0JAAMP1Zc3LdMSAPxJDbuyKwHAoWJXdiUAOFTsyq4EAIeKXdmV' +
  'ADDrUN2qURmVAOBWMSqjEgBit+pcLcqiBIDuubpYczInAaB7se7WkAxJAEjfrRs2HuMRANwwCIAAIAAgAAKAAIAACAACAAIg' +
  'AAgACIAAIAAgAAKAACAACAACgAAgAAgAAoAAIAAIAAIgAJ4MBAABEAAQAARAAEAAEAABAAFAAAQABAABEAAQAARAAEAAEAAB' +
  'AAFAAAQABAABEAAQAAFAAEAABAABAAEQAAQABEAAEAA3bDzGIwDkbthvYUiGJADk7tavYE7mJAAUL9ZPYFEWJQAUz9X3Nyqj' +
  'EgDcKkZlVAJA5lZ9fLuyKwHAoWJXdiUAOFTsyq4EAIeKXdmVADDwUH150zItAcCf1LAruxIAHCp2ZVcCgEPFruxKAHCo2JVd' +
  'CQCzDtWtGpVRCQBuFaMyKgEgdqvO1aIsSgDonquLNSdzEgC6F+tuDcmQBID03bph4zEeAcANgwAIAAIAAiAACAAIgAAgACAA' +
  'AoAAgAAIAAIAAiAACAACgAAgAAgAAoAAIAAIAAKAACAAAuDJQAAQAAEAAUAABAAEAAEQABAABEAAQAAQAAEAAUAABAAEAAEQ' +
  'ABAABEAAQAAQAAEAARAABAAEQAAQABAAAUAAQAAEAAFww6psPAJA7q3xW4iBIQkAuffFryAD5iQAFF8WP4EGWJQAUHxWfH8N' +
  'MCoBQAAQAKMSADJvio+vAXYlAAgAAmBXAoAAIAB2JQAIAAJgVwLAwAfFl9cA0xIA/A0Ar79dCQACgADYlQAgAAiAXQkAAoAA' +
  '2JUA4F8C+7EwKgFAAPxYGJUA8O83xU/g9bcoAaD7rPgVvP7mJACkXxa/haffkAQA74v/E9g7bjwCgLcGBEAAEAAQAAFAAEAA' +
  'BAABAAEQAAQABEAAEAAEAAFAABAABAABQAAQAAQAAUAABMCTgQAgAAIAAoAACAAIAAIgACAACIAAgAAgAAIAAoAACAAIAAIg' +
  'ACAACIAAgAAgAAIAAiAACAAIgAAgACAAAoAAgAAIAAIAAiAACAAIgAAgACAAAoAAgAAIAAIAAiAACAAIgAAgAAgAAoAAIAAI' +
  'AAKAACAACAACgAAgAAgAAiAAIAAIgACAACAAAgACgAAIAAgAAiAAIAAIgACAACAAAgACgAAIAAgAAiAAIAAIgACAAAgAAgAC' +
  'IAAIAAiAACAAIAACgACAAAgAAgACIAAIAAiAACAAIAACgACAAAgAAgACIAAIAAKAACAACAACgAAgAAgAAoAAIAAC4MlAABAA' +
  'AQABQAAEAAQAARAAEAAEQABAABAAAQABQAAEAAQAARAAEAAEQABAABAAAQABEAAEAARAABAAEAABQABAAAQAAQABEAA0ALz+' +
  'AoAAgAAIAAIAAiAACAAIgAAgACAAAoAAIAAIAAKAACAAaABefwQAAUAAEAAEAAFAANAAvP4IgACAACAAGgBefwRAAEAAEAAN' +
  'AK8/AqAB4PVHAAQABAAB0ADw+iMAGgBefwRAA8DrLwBoAHj9BQANAK+/ACAD4OkXADQAvP4CgAzg6UcAkAE8/QgASoB3HwFA' +
  'FfDWIwAACAAAAgCAAAAgAAAIAAACAIAAACAAAAgAAAIAgAAAIAAACAAAAgAgAAAIAAACAIAAACAAAAgAAAIAgAAAIAAACAAA' +
  'AgCAAAAgAAAIAAACAIAAACAAAAgAAAIAgAAAIAAACAAAAgAgAD4BgAAAIAAACAAAAgCAAAAgAAAIAAACAIAAACAAAAgAAAIA' +
  'gAAAIAAACAAAAgCAAAAgAAAIAAACAIAAACAAAAgAgAAAIAAACAAAAgCAAAAgAAAIAAACAIAAACAAAAgAAAIAgAAAIAAACAAA' +
  'AgCAAAAgAAAIAAACAIAAACAAAAgAgAD4CgACAIAAACAAAAgAAAIAgAAAIAAACAAAAgCAAAAgAAAIAAACAIAAACAAAAgAAAIA' +
  'wHs3HChGi76jvlQAAAAASUVORK5CYII=';

/** Decode the base64 icon into bytes once, lazily, and cache it. */
let iconBytes: Uint8Array | null = null;

export function getIcon(): Uint8Array {
  if (!iconBytes) {
    const bin = atob(ICON_B64);
    const out = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
    iconBytes = out;
  }
  return iconBytes;
}
